campaigns/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login


app_name = "campaigns"

urlpatterns = [

    url(r'^list/$', views.CampaignListView.as_view(), name='list'),
    url(r'^detail/(?P<slug>[-\w]+)/$', views.CampaignDetailView.as_view(), name="detail"),
    url(r'^prospect/get/(?P<slug>[-\w]+)/$', views.prospect_get, name="prospect_get"),
    url(r'^prospect/get/(?P<slug>[-\w]+)/(?P<prospect_id>[0-9]+)$', views.prospect_get_with_prospect, name="prospect_get"),

    url(r'^prospect_update/add/(?P<campaign_slug>[-\w]+)/(?P<prospect_id>[0-9]+)/$',
        views.prospect_update_add, name='prospect_update_add'),

    # url('(?P<slug>[-\w]+)/(?P<pk>\d+)/$', views.posts, name='posts'),

    # path('campaign/detail/<slug:slug>/', views.CampaignDetailView.as_view(), name='detail'),

]

fls_crm/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('portal.urls', namespace='portal')),
    url(r'crm_admin/', include('crm_admin.urls', namespace='crm_admin')),
    url(r'prospects/', include('prospects.urls', namespace='prospects')),
    url(r'campaigns/', include('campaigns.urls', namespace='campaigns')),
    url(r'results/', include('results.urls', namespace='results')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

portal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login

app_name = "portal"

urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name='portal/login.html'), name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^$', views.HomeView.as_view(), name='home'),

    # url(r'^$', views.home, name='home'),

    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/update/$', views.ProfileUpdateView.as_view(), name='profile_update'),

    url(r"^password/change/$", views.password_change, name='password_change'),

]

results/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login
from django.conf.urls import url
from django_filters.views import FilterView
from .filters import ResultFilter

app_name = "results"

urlpatterns = [

    url(r'^add/(?P<campaign_slug>[-\w]+)/(?P<prospect_id>[0-9]+)/$',
        views.result_add, name='result_add'),

    url(r'^leads/$', views.LeadsListView.as_view(), name="leads_list"),
    url(r'^dncs/$', views.DNCsListView.as_view(), name="dncs_list"),
    url(r'^views/$', views.ViewsListView.as_view(), name="views_list"),

    url(r'^progress/$', FilterView.as_view(filterset_class=ResultFilter,
        template_name='results/progress.html'), name='progress'),

    # url(r'^campaign/list/$', views.CampaignListView.as_view(), name='campaign_list'),
    # path('campaign/detail/<int:pk>/', views.CampaignDetailView.as_view(), name='campaign_detail'),

]

portal/models.py
from django.db import models
import datetime
from django.db.models.signals import post_save
from django.contrib.auth.models import User as Django_User_Model
from django.urls import reverse_lazy
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)

    first_name = models.CharField(max_length=32, blank=True)
    last_name = models.CharField(max_length=32, blank=True)

    phone = models.CharField(max_length=13, blank=True)

    employee_id = models.CharField(max_length=12, blank=True)

    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    date_of_birth = models.DateField(blank=True, null=True)
    details = models.TextField(blank=True)

    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(_('staff'), default=False)
    is_superuser = models.BooleanField(_('superuser'), default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.get_email_name

    @property
    def get_display_text(self):
        if self.get_full_name:
            return self.get_full_name
        else:
            return self.__str__()

    @property
    def get_full_name(self):
        return "{} {}".format(self.first_name, self.last_name) if (self.first_name or self.last_name) else ""

    @property
    def get_email_name(self):
        email_str = str(self.email)
        return email_str[:email_str.rfind("@")]

    @property
    def get_employee_id(self):
        if self.employee_id:
            return self.employee_id
        else:
            return "Unknown"

    @property
    def get_age(self):
        try:
            return datetime.date.today() - self.date_of_birth
        except:
            return "Unknown"

    @property
    def get_leads(self):
        return self.result_set.filter(result_choice="Lead")

    @property
    def get_dncs(self):
        return self.result_set.filter(result_choice="DNC")

    @property
    def get_views(self):
        return self.result_set.filter(result_choice="View")

    @property
    def get_admin_update_url(self):
        return reverse_lazy("crm_admin:executive_update", kwargs={"id": self.id})

    @property
    def get_admin_delete_url(self):
        return reverse_lazy("crm_admin:executive_delete", kwargs={"id": self.id})

    @property
    def get_active_campaigns(self):
        return self.campaign_set.filter(is_active=True)

    @property
    def get_campaigns(self):
        return self.campaign_set.all()

    def get_leads_by_campaign(self, campaign_id):
        return self.result_set.filter(result_choice="Lead", prospect_campaign_relation__campaign_id=campaign_id)

    def get_dncs_by_campaign(self, campaign_id):
        return self.result_set.filter(result_choice="DNC", prospect_campaign_relation__campaign_id=campaign_id)

    def get_views_by_campaign(self, campaign_id):
        return self.result_set.filter(result_choice="View", prospect_campaign_relation__campaign_id=campaign_id)

portal/forms.py
from django import forms
from .models import User


class ProfileUpdateForm(forms.ModelForm):

    first_name = forms.CharField(disabled=True, required=False)
    last_name = forms.CharField(disabled=True, required=False)
    date_of_birth = forms.DateField(disabled=True, required=False)
    employee_id = forms.CharField(disabled=True, required=False)

    class Meta:

        model = User
        fields = ('first_name', 'last_name', 'email', 'phone', 'date_of_birth', 'employee_id')

portal/views.py
from django.views.generic import View, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import User
from django.urls import reverse_lazy
from .forms import ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash, get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from . import alert_messages
from results.models import Result
from django.db.models import Count, Avg, Min, Max, Sum, Q
from campaigns.models import Campaign


@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, alert_messages.PASSWORD_CHANGED_MESSAGE)
            return redirect('portal:home')
        else:
            messages.error(request, alert_messages.FORM_INVALID_MESSAGE)
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'portal/password_change.html', {
        'form': form
    })


@login_required
def home(request):
    campaigns = Campaign.objects.annotate(results=Sum("prospectcampaignrelation__result"),
                                          leads=Sum("prospectcampaignrelation__result",
                                                    filter=Q(prospectcampaignrelation__result__result_choice="Lead")),
                                          views=Sum("prospectcampaignrelation__result",
                                                    filter=Q(prospectcampaignrelation__result__result_choice="View")),
                                          dncs=Sum("prospectcampaignrelation__result",
                                                    filter=Q(prospectcampaignrelation__result__result_choice="DNC")),
                                          )
    return render(request, "portal/home.html", {"campaigns": campaigns})


class HomeView(LoginRequiredMixin, View):

    def get(self, request):
        if request.user.is_superuser:
            return redirect('crm_admin:home')
        else:
            return render(request, 'portal/home.html')

    # def get_context_data(self):
    #     context = super().get_context_data()
    #     months = "nmdsalkfm"
    #     context["months"] = months
    #     return context


class ProfileView(LoginRequiredMixin, DetailView):

    template_name = "portal/profile.html"
    context_object_name = "executive"

    def get_object(self, queryset=None):
        return self.request.user


class ProfileUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    form_class = ProfileUpdateForm
    template_name = "portal/profile_update.html"
    success_url = reverse_lazy("portal:profile_update")

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, alert_messages.PROFILE_UPDATED_MESSAGE)
        return super().form_valid(form)

portal/templates/portal/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">

<head>

    {% block full_title %}
        <title>{% block title %}base file{% endblock %} - Fine-Leap Systems</title>
    {% endblock %}

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/x-icon" href="{% static "img/logo/favicon.png" %}">
    <!-- Google Fonts
		============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
    <!-- owl.carousel CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/owl.carousel.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.transitions.css" %}">
    <!-- animate CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/animate.css" %}">
    <!-- normalize CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/normalize.css" %}">
    <!-- meanmenu icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/meanmenu.min.css" %}">
    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <!-- educate icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/educate-custon-icon.css" %}">
    <!-- morrisjs CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/morrisjs/morris.css" %}">
    <!-- mCustomScrollbar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/scrollbar/jquery.mCustomScrollbar.min.css" %}">
    <!-- metisMenu CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/metisMenu/metisMenu.min.css" %}">
    <link rel="stylesheet" href="{% static "css/metisMenu/metisMenu-vertical.css" %}">
    <!-- calendar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/calendar/fullcalendar.min.css" %}">
    <link rel="stylesheet" href="{% static "css/calendar/fullcalendar.print.min.css" %}">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <!-- responsive CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/responsive.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "css/crm_custom.css" %}">

    <link rel="stylesheet" href="{% static "css/modals.css" %}">
    <link rel="stylesheet" href="{% static "css/form/all-type-forms.css" %}">
    <link rel="stylesheet" href="{% static "css/datapicker/datepicker3.css" %}">

    <!-- modernizr JS
		============================================ -->
    <script src="{% static "js/vendor/modernizr-2.8.3.min.js" %}"></script>

</head>

<body>

{##}
{#    {% if messages %}#}
{#        {% for message in messages %}#}
{#            <span class="alert btn alert-{{ message.tags }}">{{ message }}</span>#}
{#        {% endfor %}#}
{#    {% endif %}#}

    <!-- Start Left menu area -->
    {% include "portal/left_menu.html" %}
    <!-- End Left menu area -->

    <!-- Start Welcome area -->
    <div class="all-content-wrapper">
        <!-- Start Header -->
        {% include "portal/header.html" %}
        <!-- End Header -->

        {% block content %}

        {% endblock %}

        <!-- Start Footer -->
        {% include "portal/footer.html" %}
        <!-- End Footer -->

    </div>
{##}
{#        <script>#}
{#            $("#jqueryDatePicker").datepicker();#}
{#        </script>#}


    <!-- Start Scripts -->

    <!-- jquery
		============================================ -->
    <script src="{% static "js/vendor/jquery-1.12.4.min.js" %}"></script>
    <!-- bootstrap JS
		============================================ -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- wow JS
		============================================ -->
    <script src="{% static "js/wow.min.js" %}"></script>
    <!-- price-slider JS
		============================================ -->
    <script src="{% static "js/jquery-price-slider.js" %}"></script>
    <!-- meanmenu JS
		============================================ -->
    <script src="{% static "js/jquery.meanmenu.js" %}"></script>
    <!-- owl.carousel JS
		============================================ -->
    <script src="{% static "js/owl.carousel.min.js" %}"></script>
    <!-- sticky JS
		============================================ -->
    <script src="{% static "js/jquery.sticky.js" %}"></script>
    <!-- scrollUp JS
		============================================ -->
    <script src="{% static "js/jquery.scrollUp.min.js" %}"></script>
    <!-- counterup JS
		============================================ -->
    <script src="{% static "js/counterup/jquery.counterup.min.js" %}"></script>
    <script src="{% static "js/counterup/waypoints.min.js" %}"></script>
    <script src="{% static "js/counterup/counterup-active.js" %}"></script>
    <!-- mCustomScrollbar JS
		============================================ -->
    <script src="{% static "js/scrollbar/jquery.mCustomScrollbar.concat.min.js" %}"></script>
    <script src="{% static "js/scrollbar/mCustomScrollbar-active.js" %}"></script>
    <!-- metisMenu JS
		============================================ -->
    <script src="{% static "js/metisMenu/metisMenu.min.js" %}"></script>
    <script src="{% static "js/metisMenu/metisMenu-active.js" %}"></script>
    <!-- morrisjs JS
		============================================ -->
    <script src="{% static "js/morrisjs/raphael-min.js" %}"></script>
    <script src="{% static "js/morrisjs/morris.js" %}"></script>
    <script src="{% static "js/morrisjs/morris-active.js" %}"></script>
    <!-- morrisjs JS
		============================================ -->
    <script src="{% static "js/sparkline/jquery.sparkline.min.js" %}"></script>
    <script src="{% static "js/sparkline/jquery.charts-sparkline.js" %}"></script>
    <script src="{% static "js/sparkline/sparkline-active.js" %}"></script>
    <!-- calendar JS
		============================================ -->
    <script src="{% static "js/calendar/moment.min.js" %}"></script>
    <script src="{% static "js/calendar/fullcalendar.min.js" %}"></script>
    <script src="{% static "js/calendar/fullcalendar-active.js" %}"></script>
    <!-- plugins JS
		============================================ -->
    <script src="{% static "js/plugins.js" %}"></script>
    <!-- main JS
		============================================ -->
    <script src="{% static "js/main.js" %}"></script>
    <!-- tawk chat JS
		============================================ -->
    <script src="{% static "js/tawk-chat.js" %}"></script>

    <!-- End Scripts -->
    <script src="{% static "js/tab.js" %}"></script>

    <script src="{% static "js/icheck/icheck.min.js" %}"></script>
    <script src="{% static "js/icheck/icheck-active.js" %}"></script>


    <script src="{% static "js/datapicker/bootstrap-datepicker.js" %}"></script>
    <script src="{% static "js/datapicker/datepicker-active.js" %}"></script>



</body>

</html>

portal/templates/portal/home.html
{% extends "portal/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

    <div class="container bg-light text-center">
        <h3 class="text-center text-primary">Welcome to FLS-CMS</h3>
        <br>

        <h5>A Content Management Systems for Calling with your ease.</h5>
        <br>

        <a href="{% url "campaigns:list" %}"><button class="btn btn-primary white">Go for campaigns</button> </a>

    </div>

    <br><br><br>

{% endblock %}

portal/templates/portal/left_menu.html
    {% load static %}
    <style>
        .fa-lightgray{
            color: #8d9498!important;
        }
    </style>
    <div class="left-sidebar-pro">
        <nav id="sidebar" class="">
            <div class="sidebar-header">
                <a href="{% url "portal:home" %}"><img class="main-logo" src="{% static "img/logo/logosn.png" %}" alt="" /><br><span class="main-logo">Fine-Leap Systems</span></a>
                <strong><a href="{% url "portal:home" %}"><img src="{% static "img/logo/logosn.png" %}" alt="" /></a></strong>
            </div>
            <div class="left-custom-menu-adp-wrap comment-scrollbar">
                <nav class="sidebar-nav left-sidebar-menu-pro">
                    <ul class="metismenu" id="menu1">
                        <li>
                            <a title="Landing Page" href="{% url "campaigns:list" %}" aria-expanded="false"><span class="educate-icon educate-project icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Campaigns</span></a>
                        </li>

                        <li>
                            <a title="Landing Page" href="{% url "results:leads_list" %}" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Leads</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url "results:views_list" %}" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Views</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url "results:dncs_list" %}" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">DNCS</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url "results:progress" %}" aria-expanded="false"><span class="fa fa-lightgray fa-area-chart icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Progress</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url "portal:profile_update" %}" aria-expanded="false"><span class="educate-icon educate-professor icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Profile</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url "portal:logout" %}" aria-expanded="false"><span class="fa fa-lightgray fa-power-off icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Logout</span></a>
                        </li>

                    </ul>
                </nav>
            </div>
        </nav>
    </div>

portal/templates/portal/login.html
{% load crispy_forms_tags %}
{% load static %}
<!doctype html>
<html class="no-js" lang="en">

<head>

    {% block full_title %}
        <title>{% block title %}Login{% endblock %} | Fine-Leap Systems</title>
    {% endblock %}

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicon
		============================================ -->



    <link rel="shortcut icon" type="image/x-icon" href="{% static "img/logo/favicon.png" %}">
    <!-- Google Fonts
		============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
    <!-- owl.carousel CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/owl.carousel.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.transitions.css" %}">
    <!-- animate CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/animate.css" %}">
    <!-- normalize CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/normalize.css" %}">
    <!-- meanmenu icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/meanmenu.min.css" %}">
    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <!-- educate icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/educate-custon-icon.css" %}">
    <!-- morrisjs CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/morrisjs/morris.css" %}">
    <!-- mCustomScrollbar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/scrollbar/jquery.mCustomScrollbar.min.css" %}">
    <!-- metisMenu CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/metisMenu/metisMenu.min.css" %}">
    <link rel="stylesheet" href="{% static "css/metisMenu/metisMenu-vertical.css" %}">
    <!-- calendar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/calendar/fullcalendar.min.css" %}">
    <link rel="stylesheet" href="{% static "css/calendar/fullcalendar.print.min.css" %}">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <!-- responsive CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/responsive.css" %}">
    <!-- modernizr JS
		============================================ -->
    <script src="{% static "js/vendor/modernizr-2.8.3.min.js" %}"></script>



</head>

<body>


	<div class="error-pagewrap">
		<div class="error-page-int">
			<div class="text-center m-b-md custom-login">
				<h3>PLEASE LOGIN TO FLS-CRM</h3>
			</div>
			<div class="content-error">
				<div class="hpanel">
                    <div class="panel-body">
                        <form action="#" id="loginForm" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
{#                            <div class="form-group">#}
{#                                <label class="control-label" for="username">Username</label>#}
{#                                <input type="text" placeholder="example@gmail.com" title="Please enter you username" required="" value="" name="username" id="username" class="form-control">#}
{#                                <span class="help-block small">Your unique username to app</span>#}
{#                            </div>#}
{#                            <div class="form-group">#}
{#                                <label class="control-label" for="password">Password</label>#}
{#                                <input type="password" title="Please enter your password" placeholder="******" required="" value="" name="password" id="password" class="form-control">#}
{#                                <span class="help-block small">Yur strong password</span>#}
{#                            </div>#}
                            <button type="submit" class="btn btn-success btn-block loginbtn">Login</button>
                        </form>
                    </div>
                </div>
			</div>
			<div class="text-center login-footer">
				<p>Copyright © 2018. All rights reserved. Template by <a href="https://colorlib.com/wp/templates/">Colorlib</a></p>
			</div>
		</div>
    </div>

    <script src="{% static "js/vendor/jquery-1.12.4.min.js" %}"></script>
    <!-- bootstrap JS
		============================================ -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- wow JS
		============================================ -->
    <script src="{% static "js/wow.min.js" %}"></script>
    <!-- price-slider JS
		============================================ -->
    <script src="{% static "js/jquery-price-slider.js" %}"></script>
    <!-- meanmenu JS
		============================================ -->
    <script src="{% static "js/jquery.meanmenu.js" %}"></script>
    <!-- owl.carousel JS
		============================================ -->
    <script src="{% static "js/owl.carousel.min.js" %}"></script>
    <!-- sticky JS
		============================================ -->
    <script src="{% static "js/jquery.sticky.js" %}"></script>
    <!-- scrollUp JS
		============================================ -->
    <script src="{% static "js/jquery.scrollUp.min.js" %}"></script>
    <!-- counterup JS
		============================================ -->
    <script src="{% static "js/counterup/jquery.counterup.min.js" %}"></script>
    <script src="{% static "js/counterup/waypoints.min.js" %}"></script>
    <script src="{% static "js/counterup/counterup-active.js" %}"></script>
    <!-- mCustomScrollbar JS
		============================================ -->
    <script src="{% static "js/scrollbar/jquery.mCustomScrollbar.concat.min.js" %}"></script>
    <script src="{% static "js/scrollbar/mCustomScrollbar-active.js" %}"></script>
    <!-- metisMenu JS
		============================================ -->
    <script src="{% static "js/metisMenu/metisMenu.min.js" %}"></script>
    <script src="{% static "js/metisMenu/metisMenu-active.js" %}"></script>
    <!-- morrisjs JS
		============================================ -->
    <script src="{% static "js/morrisjs/raphael-min.js" %}"></script>
    <script src="{% static "js/morrisjs/morris.js" %}"></script>
    <script src="{% static "js/morrisjs/morris-active.js" %}"></script>
    <!-- morrisjs JS
		============================================ -->
    <script src="{% static "js/sparkline/jquery.sparkline.min.js" %}"></script>
    <script src="{% static "js/sparkline/jquery.charts-sparkline.js" %}"></script>
    <script src="{% static "js/sparkline/sparkline-active.js" %}"></script>
    <!-- calendar JS
		============================================ -->
    <script src="{% static "js/calendar/moment.min.js" %}"></script>
    <script src="{% static "js/calendar/fullcalendar.min.js" %}"></script>
    <script src="{% static "js/calendar/fullcalendar-active.js" %}"></script>
    <!-- plugins JS
		============================================ -->
    <script src="{% static "js/plugins.js" %}"></script>
    <!-- main JS
		============================================ -->
    <script src="{% static "js/main.js" %}"></script>
    <!-- tawk chat JS
		============================================ -->
    <script src="{% static "js/tawk-chat.js" %}"></script>

    <!-- End Scripts -->


</body>

</html>

portal/templates/portal/password_change.html
{% extends "portal/base.html" %}
{% load crispy_forms_tags %}


{% block title %}{{ executive.get_display_text }} | Profile{% endblock %}

{% block content %}


        <div class="single-pro-review-area mt-t-30 mg-b-15">
            <div class="container-fluid" style="margin: auto">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="product-payment-inner-st">
                        <ul id="myTabedu1" class="tab-review-design">
                            <li class="active"><a href="#description">Change Password</a></li>
                        </ul>
                        <div id="myTabContent" class="tab-content custom-product-edit">
                            <div class="product-tab-list tab-pane fade active in" id="description">
                               <form method="post">
                                   {% csrf_token %}
                                   {{ form|crispy }}

                                   <button type="submit" class="btn btn-primary  waves-effect waves-light">Change Password</button>

                               </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}