campaigns/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login


app_name = "campaigns"

urlpatterns = [

    url(r'^list/$', views.CampaignListView.as_view(), name='list'),
    url(r'^detail/(?P<slug>[-\w]+)/$', views.CampaignDetailView.as_view(), name="detail"),
    url(r'^prospect/get/(?P<slug>[-\w]+)/$', views.prospect_get, name="prospect_get"),
    url(r'^prospect/get/(?P<slug>[-\w]+)/(?P<prospect_id>[0-9]+)$', views.prospect_get_with_prospect, name="prospect_get"),

    url(r'^prospect_update/add/(?P<campaign_slug>[-\w]+)/(?P<prospect_id>[0-9]+)/$',
        views.prospect_update_add, name='prospect_update_add'),

    # url('(?P<slug>[-\w]+)/(?P<pk>\d+)/$', views.posts, name='posts'),

    # path('campaign/detail/<slug:slug>/', views.CampaignDetailView.as_view(), name='detail'),

]

fls_crm/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('portal.urls', namespace='portal')),
    url(r'crm_admin/', include('crm_admin.urls', namespace='crm_admin')),
    url(r'prospects/', include('prospects.urls', namespace='prospects')),
    url(r'campaigns/', include('campaigns.urls', namespace='campaigns')),
    url(r'results/', include('results.urls', namespace='results')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

portal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login

app_name = "portal"

urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name='portal/login.html'), name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^$', views.HomeView.as_view(), name='home'),

    # url(r'^$', views.home, name='home'),

    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/update/$', views.ProfileUpdateView.as_view(), name='profile_update'),

    url(r"^password/change/$", views.password_change, name='password_change'),

]

results/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login
from django.conf.urls import url
from django_filters.views import FilterView
from .filters import ResultFilter

app_name = "results"

urlpatterns = [

    url(r'^add/(?P<campaign_slug>[-\w]+)/(?P<prospect_id>[0-9]+)/$',
        views.result_add, name='result_add'),

    url(r'^leads/$', views.LeadsListView.as_view(), name="leads_list"),
    url(r'^dncs/$', views.DNCsListView.as_view(), name="dncs_list"),
    url(r'^views/$', views.ViewsListView.as_view(), name="views_list"),

    url(r'^progress/$', FilterView.as_view(filterset_class=ResultFilter,
        template_name='results/progress.html'), name='progress'),

    # url(r'^campaign/list/$', views.CampaignListView.as_view(), name='campaign_list'),
    # path('campaign/detail/<int:pk>/', views.CampaignDetailView.as_view(), name='campaign_detail'),

]

campaigns/models.py
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.utils.text import slugify
from django.http import HttpResponse
from results.models import Result
from django.urls import reverse_lazy
from clients.models import Client


def get_percent(a, b):
    try:
        return round((int(a)/int(b))*100, 2)
    except:
        return 0


class Campaign(models.Model):

    client = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=64)
    aim = models.CharField(max_length=128, blank=True)
    slug = models.SlugField(blank=True)
    is_active = models.BooleanField(default=True)
    script = models.TextField(blank=True)
    details = models.TextField(blank=True)
    start_date = models.DateField(blank=True)
    end_date = models.DateField(blank=True)
    executives = models.ManyToManyField('portal.User', blank=True)
    prospects = models.ManyToManyField('prospects.Prospect', blank=True, through='ProspectCampaignRelation')

    added_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    @property
    def get_active_status(self):
        return "Active" if self.is_active else "Not Active"

    @property
    def get_executives(self):
        print(self.executives.all())
        return self.executives.all()

    @property
    def get_client(self):
        return self.client

    @property
    def get_client_display_text(self):
        return self.client.get_display_text

    @property
    def get_aim(self):
        if self.aim:
            return self.aim
        else:
            return "--"

    @property
    def get_short_form(self):
        return self.name[:15]

    @property
    def get_display_text(self):
        return self.name

    @property
    def get_admin_absolute_url(self):
        return reverse_lazy("crm_admin:campaign_detail", kwargs={'slug': self.slug})

    @property
    def get_admin_update_url(self):
        return reverse_lazy("crm_admin:campaign_update", kwargs={'slug': self.slug})

    @property
    def get_admin_delete_url(self):
        return reverse_lazy("crm_admin:campaign_delete", kwargs={'slug': self.slug})

    @property
    def get_absolute_url(self):
        return reverse_lazy("campaigns:detail", kwargs={'slug': self.slug})

    @property
    def get_all_prospects(self):
        return self.prospects.all()

    @property
    def prospects_attempted(self):
        return self.prospects.filter(prospectcampaignrelation__attempted=True)

    @property
    def prospects_non_attempted(self):
        return self.prospects.filter(prospectcampaignrelation__attempted=False)

    @property
    def prospect_get(self):
        f_prospect = self.prospects_non_attempted.first()
        if f_prospect:
            f_prospect.prospectcampaignrelation.make_attempted()
            return f_prospect
        else:
            return False

    @property
    def get_all_leads(self):
        return Result.objects.filter(prospect_campaign_relation__campaign=self, result_choice="Lead")

    @property
    def get_leads_percent(self):
        return get_percent(self.get_all_leads.count(), self.get_all_prospects.count())

    @property
    def get_attempted_prospects_percent(self):
        return get_percent(self.prospects_attempted.count(), self.get_all_prospects.count())

    @property
    def get_non_attempted_prospects_percent(self):
        return get_percent(self.prospects_non_attempted.count(), self.get_all_prospects.count())

    @property
    def get_leads_percent_by_attempts(self):
        return get_percent(self.get_all_leads.count(), self.prospects_attempted.count())

    @property
    def get_all_views(self):
        return Result.objects.filter(prospect_campaign_relation__campaign=self, result_choice="View")

    @property
    def get_all_dncs(self):
        return Result.objects.filter(prospect_campaign_relation__campaign=self, result_choice="DNC")


def assign_slug(sender, instance, *args, **kwargs):
    slug_text = slugify(instance.name)
    if instance.slug != slug_text:
        instance.slug = slug_text
        instance.save()


pre_save.connect(assign_slug, sender=Campaign)


class ProspectCampaignRelation(models.Model):
    prospect = models.OneToOneField('prospects.Prospect', on_delete=models.CASCADE)
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    from_date = models.DateField(auto_now_add=True)
    attempted = models.BooleanField(default=False)
    details = models.TextField(blank=True)

    def __str__(self):
        return "{} -- {}".format(self.prospect, self.campaign)

    def make_attempted(self):
        self.attempted = True
        self.save()
        """ Remember to use .filter with update method if this got slow"""

    class Meta:
        unique_together = ('prospect', 'campaign')

campaigns/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DeleteView, UpdateView, FormView, DetailView
from .models import Campaign, ProspectCampaignRelation
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from results.forms import ResultAddForm
from prospects.forms import ProspectUpdateAddForm
from prospects.models import Prospect, ProspectUpdate
from django.contrib import messages
from . import alert_messages


class CampaignListView(LoginRequiredMixin, ListView):

    model = Campaign
    template_name = "campaigns/list.html"
    context_object_name = "campaigns"

    def get_queryset(self):
        return super().get_queryset().filter(executives__in=(self.request.user, ), is_active=True)


class CampaignDetailView(LoginRequiredMixin, DetailView):

    model = Campaign
    template_name = "campaigns/detail.html"
    context_object_name = "campaign"

    def get_object(self, queryset=None):
        campaign = super().get_object()
        if self.request.user in campaign.executives.all():
            return campaign
        else:
            raise Http404("No Campaign Found")


def prospect_get(request, slug):
    campaign = get_object_or_404(Campaign, slug=slug, executives__in=(request.user, ))
    prospect = campaign.prospect_get
    prospect_update_add_form = ProspectUpdateAddForm()
    print(555555)
    print(prospect_update_add_form)
    context = {'prospect': prospect, 'campaign': campaign, "prospect_update_add_form": prospect_update_add_form}
    return render(request, 'campaigns/prospect_get.html', context)


def prospect_get_with_prospect(request, slug, prospect_id):
    campaign = get_object_or_404(Campaign, slug=slug, executives__in=(request.user, ))
    prospect = get_object_or_404(Prospect, id=prospect_id, prospectcampaignrelation__campaign=campaign)
    prospect_update_add_form = ProspectUpdateAddForm()

    context = {'prospect': prospect, 'campaign': campaign, "prospect_update_add_form": prospect_update_add_form}
    return render(request, 'campaigns/prospect_get.html', context)


def prospect_update_add(request, campaign_slug, prospect_id):
    form = ProspectUpdateAddForm(request.POST or None)
    if request.POST and form.is_valid():
        form.save(commit=False)
        form.instance.prospect_campaign_relation = get_object_or_404(ProspectCampaignRelation, campaign__slug=campaign_slug, prospect__id=prospect_id)
        form.instance.by = request.user
        form.instance.save()
        messages.success(request, alert_messages.PROSPECT_UPDATE_ADDED_MESSAGE)
    else:
        messages.success(request, alert_messages.PROSPECT_UPDATE_FORM_INVLAID_MESSAGE)
    return redirect("campaigns:prospect_get", slug=campaign_slug, prospect_id=prospect_id)

campaigns/templates/campaigns/assign_campaign.html
{% extends "admin/base_site.html" %}

{% block content %}
    <form action="" method="post">
      {% csrf_token %}
        <p>
        Are you sure you want to assign following prospects to campaign?
        </p>
      {% for prospect in prospects %}
        <p>
          {{ prospect }}
        </p>
        <input type="hidden" name="_selected_action" value="{{ prospect.pk }}" />
      {% endfor %}

      <input type="hidden" name="action" value="assign_campaign" />
        <h4>Please select a Campaign from Dropdown </h4>

        <select name="campaign_id">
            {% for campaign in campaigns %}
                        <option value={{ campaign.id }}>{{ campaign.name }}</option>
            {% endfor %}
        </select>
      <input type="submit" name="assign" value="Assign"/>
    </form>
{% endblock %}

campaigns/templates/campaigns/detail.html
{% extends "portal/base.html" %}
{% load static %}
{% load result_tags %}

{% block title %}dCampaigns{% endblock %}

{% block content %}

    <div class="modal-edu-general text-center">
                            <div class="modal-dialog" style="width: 60%">
                                <div class="modal-content">
                                    <div class="modal-header header-color-modal bg-color-1">
                                        <h4 class="modal-title">{{ campaign.name }}</h4>
                                    </div>
                                    <div class="modal-body">
                                        <i class="educate-icon educate-calender modal-check-pro"></i>
                                        <h4>Aim : {{ campaign.get_aim }}</h4>
                                        <p><b>Description : </b>{{ campaign.details }}</p>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="{% url "campaigns:prospect_get" slug=campaign.slug %}">Get Prospect</a>
                                    </div>
                                </div>
                            </div>
                        </div>
    <div class="clearfix"></div>
    <br><br><br>

{% endblock %}

campaigns/templates/campaigns/list.html
{% extends "portal/base.html" %}
{% load result_tags %}
{% load static %}
{% block title %}Campaigns{% endblock %}
{% block content %}
        <div class="product-status mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-status-wrap drp-lst">
                            <h4>Campaigns List</h4>
                            <div class="add-product">
                                <a href="add-department.html">Add Query</a>
                            </div>
                            <div class="asset-inner">
                                {% if campaigns %}
                                    <table>
                                        <tr>
                                            <th>No</th>
                                            <th>Name</th>
                                            <th>Status</th>
                                            <th>Start</th>
                                            <th>End</th>
                                            <th>Leads</th>
                                            <th>Views</th>
                                            <th>DNCS</th>
                                            <th>Action</th>
                                        </tr>

                                        {% for campaign in campaigns %}

                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td>{{ campaign.get_display_text }}</td>
                                                <td>
                                                    <button class="pd-setting">{{ campaign.is_active }}</button>
                                                </td>
                                                <td>{{ campaign.start_date }}</td>
                                                <td>{{ campaign.end_date }}</td>
                                                <td>{% get_leads_by_campaign campaign_id=campaign.id executive_id=user.id %}</td>
                                                <td>{% get_views_by_campaign campaign_id=campaign.id executive_id=user.id %}</td>
                                                <td>{% get_dncs_by_campaign campaign_id=campaign.id executive_id=user.id %}</td>
                                                <td>
                                                    <a href="{{ campaign.get_absolute_url }}">
                                                        <button data-toggle="tooltip" title="Go" class="pd-setting-ed"><i class="fa fa-eye" aria-hidden="true"></i></button>
                                                    </a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </table>
                                {% else %}
                                    <h4>No Campaigns Yet</h4>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

campaigns/templates/campaigns/list2.html
{% extends "portal/base.html" %}
{% load static %}
{% block title %}Campaigns{% endblock %}

{% block content %}


    <div class="contacts-area mg-b-15">
            <div class="container-fluid">
                {%  if campaigns %}
                    <div class="row">
                        {% for campaign in campaigns %}
                            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                                <div class="bg-primary panel-heading text-center">
                                    <h3 style="color: white!important;">{{ campaign.get_short_form }}</h3>
                                </div>
                                <div class="hpanel hblue contact-panel contact-panel-cs responsive-mg-b-30">
                                    <div class="panel-body custom-panel-jw">
                                        <p class="all-pro-ad">Campaign other name/slogun etc</p>
                                        <p>{{ campaign.details }}</p>
                                    </div>
                                    <div class="course-des">
                                        <p><span><i class="fa fa-clock"></i></span> <b>Leads:</b> 6 Months</p>
                                        <p><span><i class="fa fa-clock"></i></span> <b>Views:</b> Jane Doe</p>
                                        <p><span><i class="fa fa-clock"></i></span> <b>DNC:</b> 100+</p>
                                    </div>
                                        <a href="{% url "campaigns:detail" slug=campaign.slug %}"><button class="btn btn-primary waves-effect waves-light btn-block">Goto Camapign</button> </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                        <span class="alert alert-warning " >No Campaigns</span>
                {% endif %}
            </div>
        </div>

{% endblock %}

campaigns/templates/campaigns/prospect_get.html
{% extends "portal/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container">
    <div class="row panel panel-primary " style="margin-top:2%;">
        <div class="panel-body">
            {% if prospect %}
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <ul class="nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#basic_information" class="text-primary"><i class="fa fa-indent"></i> Basic Information</a></li>
                            <li><a data-toggle="tab" href="#script" class="text-primary"><i class="fa fa-bookmark-o"></i> Script</a></li>
                        </ul>
                        <div class="tab-content">
                                    <div id="basic_information" class="tab-pane fade in active">
                                        <div class="table-responsive panel">
                                            <table class="table">
                                                <tbody>
                                                        <tr>
                                                            <td class="text-primary"><i class="fa fa-user"></i> First Name</td>
                                                            <td>{{ prospect.first_name }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-primary"><i class="fa fa-user"></i> Last Name</td>
                                                            <td>{{ prospect.last_name }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-primary"><i class="fa fa-envelope-o"></i> Email ID</td>
                                                            <td>{{ prospect.email }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-primary"><i class="glyphicon glyphicon-phone"></i> Mobile Number</td>
                                                            <td>{{ prospect.phone }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-primary"><i class="glyphicon glyphicon-globe"></i> Website</td>
                                                            <td>{{ prospect.phone }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-primary"><i class="fa fa-book"></i>Job Title</td>
                                                            <td>{{ prospect.job_title }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-primary"><i class="fa fa-university"></i> Company</td>
                                                            <td>{{ prospect.company }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-primary"><i class="fa fa-group"></i> Emp Size</td>
                                                            <td>{{ prospect.emp_size }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-primary"><i class="fa fa-group"></i> Industry Type</td>
                                                            <td>{{ prospect.industry_type }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-primary"><i class="fa fa-group"></i> Zip Code</td>
                                                            <td>{{ prospect.zip_code }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-primary"><i class="fa fa-group"></i> City</td>
                                                            <td>{{ prospect.city }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-primary"><i class="fa fa-group"></i> State</td>
                                                            <td>{{ prospect.state }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-primary"><i class="fa fa-flag"></i> Country</td>
                                                            <td>{{ prospect.country }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-primary"><i class="fa fa-list-ol"></i> Details</td>
                                                            <td>{{ prospect.details }}</td>
                                                        </tr>
                                                </tbody>
                                            </table>
                                        </div>

                                        <div class="panel text-muted">
                                            <div class="">
                                                <h4 class="text-center">Add Response</h4>
                                                <form method="post" action="{% url 'results:result_add' campaign_slug=campaign.slug prospect_id=prospect.id %}">
                                                {% csrf_token %}
                                                <div class="form-group col-lg-6">
                                                    <div class="row">
                                                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                                            <label class="login2 pull-left pull-left-pro">Select Result Response</label>
                                                        </div>
                                                        <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
                                                            <div class="bt-df-checkbox pull-left">
                                                                <div class="row">
                                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                                        <div class="i-checks pull-left">
                                                                            <label>
                                                                                    <input name="result_choice" type="radio" checked value="View"> <i></i>View</label>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                                        <div class="i-checks pull-left">
                                                                            <label>
                                                                                    <input name="result_choice" type="radio" value="Lead"> <i></i>Lead</label>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                                        <div class="i-checks pull-left">
                                                                            <label>
                                                                                    <input name="result_choice" type="radio" value="CB"> <i></i>Callback</label>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                                        <div class="i-checks pull-left">
                                                                            <label>
                                                                                <input name="result_choice" type="radio" value="DNC" > <i></i> <span class="basic-ds-n">DNC</span></label>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-group col-lg-6">
                                                    <label for="result_details">Add Message</label>
                                                    <div class="form-">
                                                        <textarea id="result_details" name="result_details"></textarea>
                                                    </div>
                                                </div>
                                                <div class="text-center">
                                                    <input class="btn btn-primary" type="submit" value="Submit">
                                                </div>
                                            </form>
                                            </div>
                                        </div>
                                    </div>

                                    <div id="script" class="tab-pane fade">
                                        <div class="table-responsive panel">
                                            <br><br>
                                            <p><span class="text-primary"><b>Script : </b></span> {{ campaign.script }}</p>
                                        </div>
                                    </div>
                                </div>
                    </div>
                </div>

                <form method="post" action="{% url 'campaigns:prospect_update_add' campaign_slug=campaign.slug prospect_id=prospect.id %}">
                    {% csrf_token %}

                    {{ prospect_update_add_form|crispy }}

                    <input class="btn btn-primary" type="submit" value="Submit Changes">

                </form>


            {% else %}
                <span class="alert alert-warning">No more prospects</span>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}