campaigns/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login


app_name = "campaigns"

urlpatterns = [

    url(r'^list/$', views.CampaignListView.as_view(), name='list'),
    url(r'^detail/(?P<slug>[-\w]+)/$', views.CampaignDetailView.as_view(), name="detail"),
    url(r'^prospect/get/(?P<slug>[-\w]+)/$', views.prospect_get, name="prospect_get"),
    url(r'^prospect/get/(?P<slug>[-\w]+)/(?P<prospect_id>[0-9]+)$', views.prospect_get_with_prospect, name="prospect_get"),

    url(r'^prospect_update/add/(?P<campaign_slug>[-\w]+)/(?P<prospect_id>[0-9]+)/$',
        views.prospect_update_add, name='prospect_update_add'),

    # url('(?P<slug>[-\w]+)/(?P<pk>\d+)/$', views.posts, name='posts'),

    # path('campaign/detail/<slug:slug>/', views.CampaignDetailView.as_view(), name='detail'),

]

crm_admin/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login


app_name = "crm_admin"

urlpatterns = [

    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'^campaigns/list/$', views.CampaignListView.as_view(), name='campaign_list'),
    url(r'^campaigns/add/$', views.CampaignAddView.as_view(), name='campaign_add'),
    url(r'^campaigns/detail/(?P<slug>[-\w]+)/$', views.CampaignDetailView.as_view(), name="campaign_detail"),
    url(r'^campaigns/update/(?P<slug>[-\w]+)/$', views.CampaignUpdateView.as_view(), name="campaign_update"),
    url(r'^campaigns/delete/(?P<slug>[-\w]+)/$', views.CampaignDeleteView.as_view(), name="campaign_delete"),

    url(r'^clients/list/$', views.ClientListView.as_view(), name='client_list'),
    url(r'^clients/add/$', views.ClientAddView.as_view(), name='client_add'),
    url(r'^clients/detail/(?P<slug>[-\w]+)/$', views.ClientDetailView.as_view(), name="client_detail"),
    url(r'^clients/update/(?P<slug>[-\w]+)/$', views.ClientUpdateView.as_view(), name="client_update"),
    url(r'^clients/delete/(?P<slug>[-\w]+)/$', views.ClientDeleteView.as_view(), name="client_delete"),

    url(r"^prospects/list/$", views.ProspectListView.as_view(), name="prospect_list"),
    url(r"^prospects/add/$", views.ProspectAddView.as_view(), name="prospect_add"),
    url(r"^prospects/list/filter/$", views.ProspectListFilterView.as_view(), name="prospect_list_filter"),
    url(r'^prospects/update/(?P<id>[0-9]+)/$', views.ProspectUpdateView.as_view(), name="prospect_update"),
    url(r'^prospects/delete/(?P<id>[0-9]+)/$', views.ProspectDeleteView.as_view(), name="prospect_delete"),

    url(r"^executives/list/$", views.ExecutiveListView.as_view(), name="executive_list"),
    url(r"^executives/add/$", views.ExecutiveAddView.as_view(), name="executive_add"),
    url(r'^executives/update/(?P<id>[0-9]+)/$', views.ExecutiveUpdateView.as_view(), name="executive_update"),
    url(r'^executives/delete/(?P<id>[0-9]+)/$', views.ExecutiveDeleteView.as_view(), name="executive_delete"),

    url(r"^prospects/updates/list/filter/$", views.ProspectUpdateListFilterView.as_view(), name="prospect_update_list_filter"),
    url(r'^prospects/updates/update/(?P<id>[0-9]+)/$', views.ProspectUpdateUpdateView.as_view(), name="prospect_update_update"),
    url(r'^prospects/updates/delete/(?P<id>[0-9]+)/$', views.ProspectUpdateDeleteView.as_view(), name="prospect_update_delete"),

    url(r'^progress/$', views.ProgressFilterView.as_view(), name='progress'),

    # url(r'^campaign/list/$', views.CampaignListView.as_view(), name='campaign_list'),
    # path('campaign/detail/<int:pk>/', views.CampaignDetailView.as_view(), name='campaign_detail'),

]

fls_crm/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('portal.urls', namespace='portal')),
    url(r'crm_admin/', include('crm_admin.urls', namespace='crm_admin')),
    url(r'prospects/', include('prospects.urls', namespace='prospects')),
    url(r'campaigns/', include('campaigns.urls', namespace='campaigns')),
    url(r'results/', include('results.urls', namespace='results')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

portal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login

app_name = "portal"

urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name='portal/login.html'), name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^$', views.HomeView.as_view(), name='home'),

    # url(r'^$', views.home, name='home'),

    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/update/$', views.ProfileUpdateView.as_view(), name='profile_update'),

    url(r"^password/change/$", views.password_change, name='password_change'),

]

crm_admin/models.py
from django.db import models

# Create your models here.

crm_admin/forms.py
from django import forms
from campaigns.models import Campaign
from clients.models import Client
from django.contrib.auth.forms import UserCreationForm
from portal.models import User
from prospects.models import Prospect, ProspectUpdate


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "phone", "date_of_birth", "employee_id", "details",
                  "password1", "password2")


class CampaignUpdateForm(forms.ModelForm):

    # start_date = forms.DateField(widget=forms.SelectDateWidget(), input_formats=(""))

    class Meta:

        model = Campaign
        fields = ('client', 'name', 'aim', 'is_active', 'script', 'details', 'start_date', 'end_date', 'executives')


class CampaignAddForm(forms.ModelForm):

    class Meta:
        model = Campaign
        fields = ('client', 'name', 'aim', 'is_active', 'script', 'details', 'start_date', 'end_date', 'executives')


class ClientUpdateForm(forms.ModelForm):

    class Meta:

        model = Client
        exclude = ('added_on', 'slug', )


class ClientAddForm(forms.ModelForm):

    class Meta:
        model = Client
        exclude = ('added_on', 'slug', )


class ProspectAddForm(forms.ModelForm):

    class Meta:

        model = Prospect
        exclude = ("created_on", "updated_on")


class ProspectUpdateForm(forms.ModelForm):

    class Meta:

        model = Prospect
        exclude = ("created_on", "updated_on")

class ProspectUpdateUpdateForm(forms.ModelForm):

    class Meta:

        model = ProspectUpdate
        exclude = ("created_on", "updated_on")

crm_admin/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import View
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DeleteView, UpdateView, FormView, DetailView, CreateView
from campaigns.models import Campaign, ProspectCampaignRelation
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from . import alert_messages
from django.contrib import messages
from .forms import (CampaignUpdateForm, CampaignAddForm, ClientAddForm, ClientUpdateForm,
                    CustomUserCreationForm, ProspectAddForm, ProspectUpdateForm, ProspectUpdateUpdateForm)
from clients.models import Client
from prospects.models import Prospect, ProspectUpdate
from .filters import ProspectFilter, ResultFilter
from django_filters.views import FilterView
from portal.models import User
from prospects.filters import ProspectUpdateFilter


def superuser_required():
    def wrapper(wrapped):
        class WrappedClass(UserPassesTestMixin, wrapped):
            def test_func(self):
                return self.request.user.is_superuser

        return WrappedClass
    return wrapper


@superuser_required()
class HomeView(LoginRequiredMixin, View):
    def get(self, request):
        if request.user.is_superuser:
            return render(request, 'crm_admin/home.html')
        else:
            return redirect('portal:home')


@superuser_required()
class CampaignListView(LoginRequiredMixin, ListView):

    model = Campaign
    template_name = "crm_admin/campaigns/list.html"
    context_object_name = "campaigns"


@superuser_required()
class CampaignDetailView(LoginRequiredMixin, DetailView):

    model = Campaign
    template_name = "campaigns/detail.html"
    context_object_name = "campaign"


@superuser_required()
class CampaignUpdateView(LoginRequiredMixin, UpdateView):

    model = Campaign
    form_class = CampaignUpdateForm
    template_name = "crm_admin/campaigns/update.html"
    success_url = reverse_lazy("crm_admin:campaign_list")

    def form_valid(self, form):
        messages.success(self.request, alert_messages.CAMPAIGN_UPDATED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class CampaignAddView(LoginRequiredMixin, CreateView):

    model = Campaign
    form_class = CampaignAddForm
    template_name = "crm_admin/campaigns/add.html"
    success_url = reverse_lazy("crm_admin:campaign_list")

    def form_valid(self, form):
        messages.success(self.request, alert_messages.CAMPAIGN_ADDED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class CampaignDeleteView(LoginRequiredMixin, DeleteView):

    model = Campaign
    template_name = "crm_admin/campaigns/delete.html"
    context_object_name = "campaign"
    success_url = reverse_lazy("crm_admin:campaign_list")

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, alert_messages.CAMPAIGN_DELETED_MESSAGE)
        return super().delete(self, request, *args, **kwargs)


@superuser_required()
class ClientListView(LoginRequiredMixin, ListView):

    model = Client
    template_name = "crm_admin/clients/list.html"
    context_object_name = "clients"


@superuser_required()
class ClientDetailView(LoginRequiredMixin, DetailView):

    model = Client
    template_name = "crm_admin/clients/detail.html"
    context_object_name = "client"


@superuser_required()
class ClientUpdateView(LoginRequiredMixin, UpdateView):

    model = Client
    form_class = ClientUpdateForm
    template_name = "crm_admin/clients/update.html"
    success_url = reverse_lazy("crm_admin:client_list")

    def form_valid(self, form):
        messages.success(self.request, alert_messages.CLIENT_UPDATED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class ClientAddView(LoginRequiredMixin, CreateView):

    model = Client
    form_class = ClientAddForm
    template_name = "crm_admin/clients/add.html"
    success_url = reverse_lazy("crm_admin:client_list")

    def form_valid(self, form):
        messages.success(self.request, alert_messages.CLIENT_ADDED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class ClientDeleteView(LoginRequiredMixin, DeleteView):

    model = Client
    template_name = "crm_admin/clients/delete.html"
    context_object_name = "client"
    success_url = reverse_lazy("crm_admin:client_list")

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, alert_messages.CLIENT_DELETED_MESSAGE)
        return super().delete(self, request, *args, **kwargs)


@superuser_required()
class ProspectListView(LoginRequiredMixin, ListView):

    model = Prospect
    template_name = "crm_admin/prospects/list.html"
    context_object_name = "prospects"


@superuser_required()
class ProspectListFilterView(LoginRequiredMixin, FilterView):

    filterset_class = ProspectFilter
    template_name = "crm_admin/prospects/list_filter.html"
    context_object_name = "prospects"


@superuser_required()
class ProspectAddView(LoginRequiredMixin, CreateView):

    model = Prospect
    form_class = ProspectAddForm
    template_name = "crm_admin/prospects/add.html"
    success_url = reverse_lazy("crm_admin:prospect_list_filter")

    def form_valid(self, form):
        messages.success(self.request, alert_messages.PROSPECT_ADDED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class ProspectUpdateView(LoginRequiredMixin, UpdateView):

    model = Prospect
    template_name = "crm_admin/prospects/update.html"
    success_url = reverse_lazy("crm_admin:prospect_list_filter")
    form_class = ProspectUpdateForm
    slug_field = "id"
    slug_url_kwarg = "id"

    def form_valid(self, form):
        messages.success(self.request, alert_messages.PROSPECT_UPDATED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class ProspectDeleteView(LoginRequiredMixin, DeleteView):

    model = Prospect
    template_name = "crm_admin/prospects/delete.html"
    context_object_name = "prospect"
    success_url = reverse_lazy("crm_admin:prospect_list_filter")
    slug_field = "id"
    slug_url_kwarg = "id"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, alert_messages.PROSPECT_DELETED_MESSAGE)
        return super().delete(self, request, *args, **kwargs)


@superuser_required()
class ExecutiveListView(LoginRequiredMixin, ListView):

    model = User
    template_name = "crm_admin/executives/list.html"
    context_object_name = "executives"

    def get_queryset(self):
        qs = super().get_queryset().filter(is_staff=False, is_superuser=False)
        return qs


@superuser_required()
class ExecutiveUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = "crm_admin/executives/update.html"
    context_object_name = "executive"
    fields = ("first_name", "last_name", "email", "phone", "employee_id", "date_of_birth", "details")
    success_url = reverse_lazy("crm_admin:executive_list")

    slug_field = "id"
    slug_url_kwarg = "id"

    def form_valid(self, form):
        messages.success(self.request, alert_messages.EXECUTIVE_UPDATED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class ExecutiveDeleteView(LoginRequiredMixin, DeleteView):

    model = User
    template_name = "crm_admin/executives/delete.html"
    context_object_name = "executive"
    success_url = reverse_lazy("crm_admin:executive_list")
    slug_field = "id"
    slug_url_kwarg = "id"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, alert_messages.EXECUTIVE_DELETED_MESSAGE)
        return super().delete(self, request, *args, **kwargs)


@superuser_required()
class ProgressFilterView(LoginRequiredMixin, FilterView):

    filterset_class = ResultFilter
    template_name = 'crm_admin/progress/progress.html'


class ExecutiveAddView(CreateView):

    form_class = CustomUserCreationForm
    model = User
    template_name = "crm_admin/executives/add.html"
    success_url = reverse_lazy("crm_admin:executive_list")

    def form_valid(self, form):
        messages.success(self.request, alert_messages.EXECUTIVE_ADDED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class ProspectUpdateListFilterView(LoginRequiredMixin, FilterView):

    filterset_class = ProspectUpdateFilter
    context_object_name = "prospect_updates"
    template_name = 'crm_admin/prospect_updates/list_filter.html'


@superuser_required()
class ProspectUpdateUpdateView(LoginRequiredMixin, UpdateView):

    model = ProspectUpdate
    template_name = "crm_admin/prospect_updates/update.html"
    success_url = reverse_lazy("crm_admin:prospect_update_list_filter")
    form_class = ProspectUpdateUpdateForm
    slug_field = "id"
    slug_url_kwarg = "id"

    def form_valid(self, form):
        messages.success(self.request, alert_messages.PROSPECT_UPDATE_UPDATED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class ProspectUpdateDeleteView(LoginRequiredMixin, DeleteView):

    model = ProspectUpdate
    template_name = "crm_admin/prospect_updates/delete.html"
    context_object_name = "prospect_update"
    success_url = reverse_lazy("crm_admin:prospect_update_list_filter")
    slug_field = "id"
    slug_url_kwarg = "id"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, alert_messages.PROSPECT_UPDATE_DELETED_MESSAGE)
        return super().delete(self, request, *args, **kwargs)

crm_admin/templates/crm_admin/prospect_updates/delete.html
{% extends "crm_admin/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Delete Prospect{% endblock %}
{% block content %}

    <div class="container text-center">
        <div class="jumbotron col-lg-6">
            <form method="post">
            {% if prospect.is_campaign_attempted %}
                <span class="alert alert-danger btn-block">Prospect to be attempted in campaign ({{ prospect.prospectcampaignrelation.campaign.get_display_text }})</span>
            {% endif %}
            <h3>{{ prospect.get_display_text }}</h3>
            <h4>Make sure your really wants to delete this Prospect</h4>
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-danger" value="Delete">
        </form>
        </div>
    </div>
    <br><br><br>

{% endblock %}

crm_admin/templates/crm_admin/prospect_updates/detail.html
{% extends "crm_admin/base.html" %}
{% load static %}
{% load result_tags %}

{% block title %}Campaigns{% endblock %}

{% block content %}

    <div class="modal-edu-general text-center">
                            <div class="modal-dialog" style="width: 60%">
                                <div class="modal-content">
                                    <div class="modal-header header-color-modal bg-color-1">
                                        <h4 class="modal-title">{{ campaign.name }}</h4>
                                    </div>
                                    <div class="modal-body">
                                        <i class="educate-icon educate-calender modal-check-pro"></i>
                                        <h4>Aim : {{ campaign.get_aim }}</h4>
                                        <p><b>Description : </b>{{ campaign.details }}</p>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="{% url "campaigns:prospect_get" slug=campaign.slug %}">Get Prospect</a>
                                    </div>
                                </div>
                            </div>
                        </div>
    <div class="clearfix"></div>
    <br><br><br>

{% endblock %}

crm_admin/templates/crm_admin/prospect_updates/list.html
{% extends "crm_admin/base.html" %}
{% load result_tags %}
{% load static %}
{% block title %}All Prospect{% endblock %}

{% block content %}



            <div class="data-table-area mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="sparkline13-list">
                            <div class="sparkline13-hd">
                                <div class="main-sparkline13-hd">
                                    <h1>Prospect List</h1>
                                    <div class="add-product">
                                        <a href="{% url "crm_admin:prospect_add" %}">Add Prospect</a>
                                        <a href="#">Add Prospect</a>
                                    </div>
                                </div>

                            </div>
                            <div class="sparkline13-graph">
                                <div class="datatable-dashv1-list custom-datatable-overright">
                                    <div id="toolbar">
                                        <select class="form-control dt-tb">
											<option value="">Export Basic</option>
											<option value="all">Export All</option>
											<option value="selected">Export Selected</option>
										</select>
                                    </div>
                                    <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true" data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true"
                                        data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                                        <thead>
                                            <tr>
                                                <th data-field="state"></th>
                                                <th data-field="id">No</th>
                                                <th data-field="name">Name</th>
                                                <th data-field="email">Email</th>
                                                <th data-field="phone">Phone</th>
                                                <th data-field="job_title">Job Title</th>
                                                <th data-field="company">Company</th>
                                                <th data-field="industry_type">Industry Type</th>
                                                <th data-field="emp_size">Emp Size</th>
                                                <th data-field="website">Website</th>
                                                <th data-field="action">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            {% for prospect in prospects %}
                                                <tr>
                                                    <td></td>
                                                    <td>{{ forloop.counter }}</td>
                                                    <td>{{ prospect.get_display_text }}</td>
                                                    <td>{{ prospect.email }}</td>
                                                    <td>{{ prospect.phone }}</td>
                                                    <td>{{ prospect.job_title }}</td>
                                                    <td>{{ prospect.company }}</td>
                                                    <td>{{ prospect.industry_type }}</td>
                                                    <td>{{ prospect.emp_size }}</td>
                                                    <td>{{ prospect.city }}</td>
                                                    <td class="datatable-ct"><a href="{{ prospect.get_admin_update_url }}"><i class="fa fa-eye"></i></a></td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

crm_admin/templates/crm_admin/prospect_updates/list2.html
{% extends "crm_admin/base.html" %}
{% load result_tags %}
{% load static %}
{% block title %}Clients{% endblock %}
{% block content %}
        <div class="product-status mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-status-wrap drp-lst">
                            <h4>Client List</h4>
                            <div class="add-product">
                                <a href="{% url "crm_admin:client_add" %}">Add Client</a>
                            </div>
                            <div class="asset-inner">
                                {% if clients %}
                                    <table>
                                        <tr>
                                            <th>No</th>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Campaigns</th>
                                            <th>Company</th>
                                            <th>Industry Type</th>
                                            <th>Emp Size</th>
                                            <th>City</th>
                                            <th>Actions</th>
                                        </tr>

                                        {% for client in clients %}

                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td>{{ client.get_display_text }}</td>
                                                <td>{{ client.email }}</td>
                                                <td>{{ client.get_campaigns.count }}</td>
                                                <td>{{ client.company }}</td>
                                                <td>{{ client.industry_type }}</td>
                                                <td>{{ client.emp_size }}</td>
                                                <td>{{ client.city }}</td>
                                                <td>
                                                    <a href="{{ client.get_admin_update_url }}">
                                                        <button data-toggle="tooltip" title="Update" class="pd-setting-ed"><i class="fa fa-eye" aria-hidden="true"></i></button>
                                                    </a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </table>
                                {% else %}
                                    <h4>No Clients Yet</h4>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

crm_admin/templates/crm_admin/prospect_updates/list_filter.html
{% extends "crm_admin/base.html" %}
{% load result_tags %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}All Prospect{% endblock %}

{% block content %}


            <div class="container">
                <form method="get">

                    <div class="row">
                        <div class="form-group col-lg-2">
                            {{ filter.form.prospect_campaign_relation__campaign|as_crispy_field }}
                        </div>
                        <div class="form-group col-lg-3">
                            {{ filter.form.by|as_crispy_field }}
                        </div>
                        <div class="form-group col-lg-3">
                            {{ filter.form.created_on|as_crispy_field }}
                        </div>
                        <div class="form-group col-lg-3">
                            {{ filter.form.is_approved|as_crispy_field }}
                        </div>
                    </div>

                    <input class="btn btn-primary" type="submit" value="Filter">
                </form>
                <br>
            </div>



<div class="data-table-area mg-b-15">
                <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="sparkline13-list">
                            <div class="sparkline13-hd">
                                <div class="main-sparkline13-hd">
                                    <h1>Prospect List</h1>
                                    <div class="add-product">
                                        <a href="{% url "crm_admin:prospect_add" %}">Add Prospect</a>
                                        <a href="#">Add Prospect</a>
                                    </div>
                                </div>

                            </div>
                            <div class="sparkline13-graph">
                                <div class="datatable-dashv1-list custom-datatable-overright">
                                    <div id="toolbar">
                                        <select class="form-control dt-tb">
											<option value="">Export Basic</option>
											<option value="all">Export All</option>
											<option value="selected">Export Selected</option>
										</select>
                                    </div>
                                    <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true" data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true"
                                        data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                                        <thead>
                                            <tr>
                                                <th data-field="state" data-checkbox="true"></th>
                                                <th data-field="id">No</th>
                                                <th data-field="name">Name</th>
                                                <th data-field="by_executive">Executive</th>
                                                <th data-field="campaign">Campaign</th>
                                                <th data-field="created_on">Created On</th>
                                                <th data-field="approved">Approved</th>
                                                <th data-field="action">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            {% for prospect_update in prospect_updates %}
                                                <tr>
                                                    <td></td>
                                                    <td>{{ forloop.counter }}</td>
                                                    <td>{{ prospect_update.prospect_campaign_relation.prospect.get_display_text }}</td>
                                                    <td>{{ prospect_update.by.get_display_text }}</td>
                                                    <td>{{ prospect_update.prospect_campaign_relation.campaign.get_display_text }}</td>
                                                    <td>{{ prospect_update.created_on }}</td>
                                                    <td>{{ prospect_update.is_approved }}</td>
                                                    <td class="datatable-ct"><a href="{{ prospect_update.get_admin_update_url }}"><i class="fa fa-eye"></i></a></td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>



{% endblock %}