crm_admin/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login


app_name = "crm_admin"

urlpatterns = [

    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'^campaigns/list/$', views.CampaignListView.as_view(), name='campaign_list'),
    url(r'^campaigns/add/$', views.CampaignAddView.as_view(), name='campaign_add'),
    url(r'^campaigns/detail/(?P<slug>[-\w]+)/$', views.CampaignDetailView.as_view(), name="campaign_detail"),
    url(r'^campaigns/update/(?P<slug>[-\w]+)/$', views.CampaignUpdateView.as_view(), name="campaign_update"),
    url(r'^campaigns/delete/(?P<slug>[-\w]+)/$', views.CampaignDeleteView.as_view(), name="campaign_delete"),

    url(r'^clients/list/$', views.ClientListView.as_view(), name='client_list'),
    url(r'^clients/add/$', views.ClientAddView.as_view(), name='client_add'),
    url(r'^clients/detail/(?P<slug>[-\w]+)/$', views.ClientDetailView.as_view(), name="client_detail"),
    url(r'^clients/update/(?P<slug>[-\w]+)/$', views.ClientUpdateView.as_view(), name="client_update"),
    url(r'^clients/delete/(?P<slug>[-\w]+)/$', views.ClientDeleteView.as_view(), name="client_delete"),

    url(r"^prospects/list/$", views.ProspectListView.as_view(), name="prospect_list"),
    url(r"^prospects/add/$", views.ProspectAddView.as_view(), name="prospect_add"),
    url(r"^prospects/list/filter/$", views.ProspectListFilterView.as_view(), name="prospect_list_filter"),
    url(r'^prospects/update/(?P<id>[0-9]+)/$', views.ProspectUpdateView.as_view(), name="prospect_update"),
    url(r'^prospects/delete/(?P<id>[0-9]+)/$', views.ProspectDeleteView.as_view(), name="prospect_delete"),

    url(r"^executives/list/$", views.ExecutiveListView.as_view(), name="executive_list"),
    url(r"^executives/add/$", views.ExecutiveAddView.as_view(), name="executive_add"),
    url(r'^executives/update/(?P<id>[0-9]+)/$', views.ExecutiveUpdateView.as_view(), name="executive_update"),
    url(r'^executives/delete/(?P<id>[0-9]+)/$', views.ExecutiveDeleteView.as_view(), name="executive_delete"),

    url(r"^prospects/updates/list/filter/$", views.ProspectUpdateListFilterView.as_view(), name="prospect_update_list_filter"),
    url(r'^prospects/updates/update/(?P<id>[0-9]+)/$', views.ProspectUpdateUpdateView.as_view(), name="prospect_update_update"),
    url(r'^prospects/updates/delete/(?P<id>[0-9]+)/$', views.ProspectUpdateDeleteView.as_view(), name="prospect_update_delete"),

    url(r'^progress/$', views.ProgressFilterView.as_view(), name='progress'),

    # url(r'^campaign/list/$', views.CampaignListView.as_view(), name='campaign_list'),
    # path('campaign/detail/<int:pk>/', views.CampaignDetailView.as_view(), name='campaign_detail'),

]

fls_crm/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('portal.urls', namespace='portal')),
    url(r'crm_admin/', include('crm_admin.urls', namespace='crm_admin')),
    url(r'prospects/', include('prospects.urls', namespace='prospects')),
    url(r'campaigns/', include('campaigns.urls', namespace='campaigns')),
    url(r'results/', include('results.urls', namespace='results')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

portal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login

app_name = "portal"

urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name='portal/login.html'), name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^$', views.HomeView.as_view(), name='home'),

    # url(r'^$', views.home, name='home'),

    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/update/$', views.ProfileUpdateView.as_view(), name='profile_update'),

    url(r"^password/change/$", views.password_change, name='password_change'),

]

results/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login
from django.conf.urls import url
from django_filters.views import FilterView
from .filters import ResultFilter

app_name = "results"

urlpatterns = [

    url(r'^add/(?P<campaign_slug>[-\w]+)/(?P<prospect_id>[0-9]+)/$',
        views.result_add, name='result_add'),

    url(r'^leads/$', views.LeadsListView.as_view(), name="leads_list"),
    url(r'^dncs/$', views.DNCsListView.as_view(), name="dncs_list"),
    url(r'^views/$', views.ViewsListView.as_view(), name="views_list"),

    url(r'^progress/$', FilterView.as_view(filterset_class=ResultFilter,
        template_name='results/progress.html'), name='progress'),

    # url(r'^campaign/list/$', views.CampaignListView.as_view(), name='campaign_list'),
    # path('campaign/detail/<int:pk>/', views.CampaignDetailView.as_view(), name='campaign_detail'),

]

crm_admin/models.py
from django.db import models

# Create your models here.

crm_admin/forms.py
from django import forms
from campaigns.models import Campaign
from clients.models import Client
from django.contrib.auth.forms import UserCreationForm
from portal.models import User
from prospects.models import Prospect, ProspectUpdate


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "phone", "date_of_birth", "employee_id", "details",
                  "password1", "password2")


class CampaignUpdateForm(forms.ModelForm):

    # start_date = forms.DateField(widget=forms.SelectDateWidget(), input_formats=(""))

    class Meta:

        model = Campaign
        fields = ('client', 'name', 'aim', 'is_active', 'script', 'details', 'start_date', 'end_date', 'executives')


class CampaignAddForm(forms.ModelForm):

    class Meta:
        model = Campaign
        fields = ('client', 'name', 'aim', 'is_active', 'script', 'details', 'start_date', 'end_date', 'executives')


class ClientUpdateForm(forms.ModelForm):

    class Meta:

        model = Client
        exclude = ('added_on', 'slug', )


class ClientAddForm(forms.ModelForm):

    class Meta:
        model = Client
        exclude = ('added_on', 'slug', )


class ProspectAddForm(forms.ModelForm):

    class Meta:

        model = Prospect
        exclude = ("created_on", "updated_on")


class ProspectUpdateForm(forms.ModelForm):

    class Meta:

        model = Prospect
        exclude = ("created_on", "updated_on")

class ProspectUpdateUpdateForm(forms.ModelForm):

    class Meta:

        model = ProspectUpdate
        exclude = ("created_on", "updated_on")

crm_admin/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import View
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DeleteView, UpdateView, FormView, DetailView, CreateView
from campaigns.models import Campaign, ProspectCampaignRelation
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from . import alert_messages
from django.contrib import messages
from .forms import (CampaignUpdateForm, CampaignAddForm, ClientAddForm, ClientUpdateForm,
                    CustomUserCreationForm, ProspectAddForm, ProspectUpdateForm, ProspectUpdateUpdateForm)
from clients.models import Client
from prospects.models import Prospect, ProspectUpdate
from .filters import ProspectFilter, ResultFilter
from django_filters.views import FilterView
from portal.models import User
from prospects.filters import ProspectUpdateFilter


def superuser_required():
    def wrapper(wrapped):
        class WrappedClass(UserPassesTestMixin, wrapped):
            def test_func(self):
                return self.request.user.is_superuser

        return WrappedClass
    return wrapper


@superuser_required()
class HomeView(LoginRequiredMixin, View):
    def get(self, request):
        if request.user.is_superuser:
            return render(request, 'crm_admin/home.html')
        else:
            return redirect('portal:home')


@superuser_required()
class CampaignListView(LoginRequiredMixin, ListView):

    model = Campaign
    template_name = "crm_admin/campaigns/list.html"
    context_object_name = "campaigns"


@superuser_required()
class CampaignDetailView(LoginRequiredMixin, DetailView):

    model = Campaign
    template_name = "campaigns/detail.html"
    context_object_name = "campaign"


@superuser_required()
class CampaignUpdateView(LoginRequiredMixin, UpdateView):

    model = Campaign
    form_class = CampaignUpdateForm
    template_name = "crm_admin/campaigns/update.html"
    success_url = reverse_lazy("crm_admin:campaign_list")

    def form_valid(self, form):
        messages.success(self.request, alert_messages.CAMPAIGN_UPDATED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class CampaignAddView(LoginRequiredMixin, CreateView):

    model = Campaign
    form_class = CampaignAddForm
    template_name = "crm_admin/campaigns/add.html"
    success_url = reverse_lazy("crm_admin:campaign_list")

    def form_valid(self, form):
        messages.success(self.request, alert_messages.CAMPAIGN_ADDED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class CampaignDeleteView(LoginRequiredMixin, DeleteView):

    model = Campaign
    template_name = "crm_admin/campaigns/delete.html"
    context_object_name = "campaign"
    success_url = reverse_lazy("crm_admin:campaign_list")

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, alert_messages.CAMPAIGN_DELETED_MESSAGE)
        return super().delete(self, request, *args, **kwargs)


@superuser_required()
class ClientListView(LoginRequiredMixin, ListView):

    model = Client
    template_name = "crm_admin/clients/list.html"
    context_object_name = "clients"


@superuser_required()
class ClientDetailView(LoginRequiredMixin, DetailView):

    model = Client
    template_name = "crm_admin/clients/detail.html"
    context_object_name = "client"


@superuser_required()
class ClientUpdateView(LoginRequiredMixin, UpdateView):

    model = Client
    form_class = ClientUpdateForm
    template_name = "crm_admin/clients/update.html"
    success_url = reverse_lazy("crm_admin:client_list")

    def form_valid(self, form):
        messages.success(self.request, alert_messages.CLIENT_UPDATED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class ClientAddView(LoginRequiredMixin, CreateView):

    model = Client
    form_class = ClientAddForm
    template_name = "crm_admin/clients/add.html"
    success_url = reverse_lazy("crm_admin:client_list")

    def form_valid(self, form):
        messages.success(self.request, alert_messages.CLIENT_ADDED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class ClientDeleteView(LoginRequiredMixin, DeleteView):

    model = Client
    template_name = "crm_admin/clients/delete.html"
    context_object_name = "client"
    success_url = reverse_lazy("crm_admin:client_list")

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, alert_messages.CLIENT_DELETED_MESSAGE)
        return super().delete(self, request, *args, **kwargs)


@superuser_required()
class ProspectListView(LoginRequiredMixin, ListView):

    model = Prospect
    template_name = "crm_admin/prospects/list.html"
    context_object_name = "prospects"


@superuser_required()
class ProspectListFilterView(LoginRequiredMixin, FilterView):

    filterset_class = ProspectFilter
    template_name = "crm_admin/prospects/list_filter.html"
    context_object_name = "prospects"


@superuser_required()
class ProspectAddView(LoginRequiredMixin, CreateView):

    model = Prospect
    form_class = ProspectAddForm
    template_name = "crm_admin/prospects/add.html"
    success_url = reverse_lazy("crm_admin:prospect_list_filter")

    def form_valid(self, form):
        messages.success(self.request, alert_messages.PROSPECT_ADDED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class ProspectUpdateView(LoginRequiredMixin, UpdateView):

    model = Prospect
    template_name = "crm_admin/prospects/update.html"
    success_url = reverse_lazy("crm_admin:prospect_list_filter")
    form_class = ProspectUpdateForm
    slug_field = "id"
    slug_url_kwarg = "id"

    def form_valid(self, form):
        messages.success(self.request, alert_messages.PROSPECT_UPDATED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class ProspectDeleteView(LoginRequiredMixin, DeleteView):

    model = Prospect
    template_name = "crm_admin/prospects/delete.html"
    context_object_name = "prospect"
    success_url = reverse_lazy("crm_admin:prospect_list_filter")
    slug_field = "id"
    slug_url_kwarg = "id"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, alert_messages.PROSPECT_DELETED_MESSAGE)
        return super().delete(self, request, *args, **kwargs)


@superuser_required()
class ExecutiveListView(LoginRequiredMixin, ListView):

    model = User
    template_name = "crm_admin/executives/list.html"
    context_object_name = "executives"

    def get_queryset(self):
        qs = super().get_queryset().filter(is_staff=False, is_superuser=False)
        return qs


@superuser_required()
class ExecutiveUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = "crm_admin/executives/update.html"
    context_object_name = "executive"
    fields = ("first_name", "last_name", "email", "phone", "employee_id", "date_of_birth", "details")
    success_url = reverse_lazy("crm_admin:executive_list")

    slug_field = "id"
    slug_url_kwarg = "id"

    def form_valid(self, form):
        messages.success(self.request, alert_messages.EXECUTIVE_UPDATED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class ExecutiveDeleteView(LoginRequiredMixin, DeleteView):

    model = User
    template_name = "crm_admin/executives/delete.html"
    context_object_name = "executive"
    success_url = reverse_lazy("crm_admin:executive_list")
    slug_field = "id"
    slug_url_kwarg = "id"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, alert_messages.EXECUTIVE_DELETED_MESSAGE)
        return super().delete(self, request, *args, **kwargs)


@superuser_required()
class ProgressFilterView(LoginRequiredMixin, FilterView):

    filterset_class = ResultFilter
    template_name = 'crm_admin/progress/progress.html'


class ExecutiveAddView(CreateView):

    form_class = CustomUserCreationForm
    model = User
    template_name = "crm_admin/executives/add.html"
    success_url = reverse_lazy("crm_admin:executive_list")

    def form_valid(self, form):
        messages.success(self.request, alert_messages.EXECUTIVE_ADDED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class ProspectUpdateListFilterView(LoginRequiredMixin, FilterView):

    filterset_class = ProspectUpdateFilter
    context_object_name = "prospect_updates"
    template_name = 'crm_admin/prospect_updates/list_filter.html'


@superuser_required()
class ProspectUpdateUpdateView(LoginRequiredMixin, UpdateView):

    model = ProspectUpdate
    template_name = "crm_admin/prospect_updates/update.html"
    success_url = reverse_lazy("crm_admin:prospect_update_list_filter")
    form_class = ProspectUpdateUpdateForm
    slug_field = "id"
    slug_url_kwarg = "id"

    def form_valid(self, form):
        messages.success(self.request, alert_messages.PROSPECT_UPDATE_UPDATED_MESSAGE)
        return super().form_valid(form)


@superuser_required()
class ProspectUpdateDeleteView(LoginRequiredMixin, DeleteView):

    model = ProspectUpdate
    template_name = "crm_admin/prospect_updates/delete.html"
    context_object_name = "prospect_update"
    success_url = reverse_lazy("crm_admin:prospect_update_list_filter")
    slug_field = "id"
    slug_url_kwarg = "id"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, alert_messages.PROSPECT_UPDATE_DELETED_MESSAGE)
        return super().delete(self, request, *args, **kwargs)

crm_admin/templates/crm_admin/footer.html
    {% load static %}
    <div class="footer-copyright-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="footer-copy-right">
                            <p>Copyright © 2018. All rights reserved. Template by <a href="https://colorlib.com/wp/templates/">Colorlib</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

crm_admin/templates/crm_admin/home.html
{% extends "crm_admin/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

    <div class="container bg-light text-center">
        <h3 class="text-center text-primary">Welcome to FLS-CMS</h3>
        <br>

        <h5>A Content Management Systems for Calling with your ease.</h5>
        <br>

    </div>

    <br><br><br>

{% endblock %}

crm_admin/templates/crm_admin/left_menu.html
    {% load static %}

        <style>
            .fa-lightgray{
                color: #8d9498!important;
            }
        </style>

        <div class="left-sidebar-pro">
        <nav id="sidebar" class="">
            <div class="sidebar-header">
                <a href="{% url "portal:home" %}"><img class="main-logo" src="{% static "img/logo/logosn.png" %}" alt="" /><br><span class="main-logo">Fine-Leap Systems</span></a>
                <strong><a href="{% url "portal:home" %}"><img src="{% static "img/logo/logosn.png" %}" alt="" /></a></strong>
            </div>
            <div class="left-custom-menu-adp-wrap comment-scrollbar">
                <nav class="sidebar-nav left-sidebar-menu-pro">
                    <ul class="metismenu" id="menu1">
                        <li>
                            <a href="{% url "crm_admin:home" %}">
                               <span class="educate-icon educate-home icon-wrap"></span>
                               <span class="mini-click-non">Dashboard</span>
                            </a>
                        </li>
                        <li>
                            <a class="has-arrow" href="{% url "crm_admin:executive_list" %}" aria-expanded="false"><span class="fa fa-lightgray fa-user-o icon-wrap"></span> <span class="mini-click-non">Executives</span></a>
                            <ul class="submenu-angle" aria-expanded="false">
                                <li><a title="All Executives" href="{% url "crm_admin:executive_list" %}"><span class="mini-sub-pro">All Executives</span></a></li>
                                <li><a title="Add Executive" href="{% url "crm_admin:executive_add" %}"><span class="mini-sub-pro">Add Executive</span></a></li>
                            </ul>
                        </li>
                        <li>
                            <a class="has-arrow" href="{% url "crm_admin:campaign_list" %}" aria-expanded="false"><span class="educate-icon educate-project icon-wrap"></span> <span class="mini-click-non">Campaigns</span></a>
                            <ul class="submenu-angle" aria-expanded="false">
                                <li><a title="All Campaigns" href="{% url "crm_admin:campaign_list" %}"><span class="mini-sub-pro">All Campaigns</span></a></li>
                                <li><a title="Add Campaign" href="{% url "crm_admin:campaign_add" %}"><span class="mini-sub-pro">Add Campaign</span></a></li>
                            </ul>
                        </li>
                        <li>
                            <a class="has-arrow" href="{% url "crm_admin:client_list" %}" aria-expanded="false"><span class="educate-icon educate-professor icon-wrap"></span> <span class="mini-click-non">Clients</span></a>
                            <ul class="submenu-angle" aria-expanded="false">
                                <li><a title="All Clients" href="{% url "crm_admin:client_list" %}"><span class="mini-sub-pro">All Clients</span></a></li>
                                <li><a title="Add Client" href="{% url "crm_admin:client_add" %}"><span class="mini-sub-pro">Add Client</span></a></li>
                            </ul>
                        </li>
                        <li>
                            <a class="has-arrow" href="{% url "crm_admin:prospect_list" %}" aria-expanded="false"><span class="fa fa-lightgray fa-address-card-o icon-wrap"></span> <span class="mini-click-non">Prospects</span></a>
                            <ul class="submenu-angle" aria-expanded="false">
                                <li><a title="All Prospects" href="{% url "crm_admin:prospect_list_filter" %}"><span class="mini-sub-pro">All Prospects</span></a></li>
                                <li><a title="Add Prospect" href="{% url "crm_admin:prospect_add" %}"><span class="mini-sub-pro">Add Prospect</span></a></li>
                            </ul>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url "crm_admin:prospect_update_list_filter" %}" aria-expanded="false"><span class="fa fa-lightgray fa-area-chart icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Propsect Updates</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url "crm_admin:progress" %}" aria-expanded="false"><span class="fa fa-lightgray fa-area-chart icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Progress</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url "portal:logout" %}" aria-expanded="false"><span class="fa fa-lightgray fa-power-off icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Logout</span></a>
                        </li>
                    </ul>
                </nav>
            </div>
        </nav>
    </div>

crm_admin/templates/crm_admin/left_menu2.html
    {% load static %}
    <div class="left-sidebar-pro">
        <nav id="sidebar" class="">
            <div class="sidebar-header">
                <a href="{% url "portal:home" %}"><img class="main-logo" src="{% static "img/logo/logosn.png" %}" alt="" /><br><span class="main-logo">Fine-Leap Systems</span></a>
                <strong><a href="{% url "portal:home" %}"><img src="{% static "img/logo/logosn.png" %}" alt="" /></a></strong>
            </div>
            <div class="left-custom-menu-adp-wrap comment-scrollbar">
                <nav class="sidebar-nav left-sidebar-menu-pro">
                    <ul class="metismenu" id="menu1">
                        <li>
                            <a title="Landing Page" href="{% url 'crm_admin:executive_list' %}" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Executives</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url 'crm_admin:campaign_list' %}" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Campaigns</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url 'crm_admin:client_list' %}" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Clients</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url 'crm_admin:prospect_list' %}" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Prospects</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url 'crm_admin:prospect_list_filter' %}" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Prospects Filter</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url "results:leads_list" %}" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Leads</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url "results:views_list" %}" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Views</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url "results:dncs_list" %}" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">DNCS</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url "crm_admin:progress" %}" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Progress</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="{% url "portal:profile_update" %}" aria-expanded="false"><span class="educate-icon educate-professor icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Profile</span></a>
                        </li>

                    </ul>
                </nav>
            </div>
        </nav>
    </div>